name: CI/CD - ese-order

on:
  push:
    paths:
      - 'services/ese-order/**'
  pull_request:
    paths:
      - 'services/ese-order/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/ese-order
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test
      - run: npm run test:cov
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ese-order:latest .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/ese-order:latest